# Site settings
title: "Buckaroo Banjai"
email: kostaris@gmail.com
description: "Πράγματα που δεν έπρεπε να συμβούν, συμβαίνουν..."
baseurl: ""
url: "http://buckaroobanjai.github.io/"
title_description: "Πράγματα που δεν έπρεπε να συμβούν, συμβαίνουν..."
title_image: "http://en.gravatar.com/userimage/8369206/3db1ee4e787816ea72198dfe031d5c8b.jpg?size=300"
google_analytics: "UA-20365477-4"
disqus_account: buckaroobanjai
github_repository: https://github.com/BuckarooBanjai/buckaroobanjai.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: kostas_bartzis
github_username:  BuckarooBanjai
linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/kostas_bartzis\">kostas bartzis</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/BuckarooBanjai/BuckarooBanjai.github.io.git\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
