title: "Buckaroo Banjai"
email: kostaris@gmail.com
description: "Πράγματα που δεν έπρεπε να συμβούν, συμβαίνουν..."
baseurl: 
url: "http://buckaroobanjai.github.io/"
title_description: "Πράγματα που δεν έπρεπε να συμβούν, συμβαίνουν..."
title_image: "https://en.gravatar.com/userimage/8369206/3db1ee4e787816ea72198dfe031d5c8b.jpg?size=300"
google_analytics: "UA-20365477-4"
disqus_account: buckaroobanjai
github_repository: https://github.com/BuckarooBanjai/buckaroobanjai.github.io
addthis_id: ra-55d9fdb6050e33c2
post_limit: 5

# Social usernames/URLs
twitter_username: kostas_bartzis
github_username:  BuckarooBanjai
linkedin_link: https://gr.linkedin.com/in/konstantinosbartzis
google_plus_link: https://plus.google.com/+kostasbartzisplus/posts

# Footer
footer_left: "Φτιαγμένο με <i class=\"fa fa-heart\"></i> από <a href=\"https://twitter.com/kostas_bartzis\">kostas bartzis</a>"
footer_right: "&lt;/&gt; στο <a href=\"https://github.com/BuckarooBanjai/BuckarooBanjai.github.io.git\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
